//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunApproachStatistics.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vault
    {
        public int vault_id { get; set; }
        public int gymnast_id { get; set; }
        public long duration { get; set; }
        public string graphdata { get; set; }
        public string videopath { get; set; }
        public Nullable<int> rating_star { get; set; }
        public Nullable<int> rating_official_D { get; set; }
        public Nullable<int> rating_official_E { get; set; }
        public System.DateTime timestamp { get; set; }
        public string context { get; set; }
        public Nullable<bool> good_jump_indication { get; set; }
        public string note { get; set; }
        public Nullable<int> vaulttype_id { get; set; }
        public int location_id { get; set; }
    
        public virtual gymnast gymnast { get; set; }
        public virtual location location { get; set; }
        public virtual vaultnumber vaultnumber { get; set; }
    }
}
