//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunApproachStatistics.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vault
    {
        public int vault_id { get; set; }
        public Nullable<int> gymnast_id { get; set; }
        public decimal duration { get; set; }
        public string graphdata { get; set; }
        public string videopath { get; set; }
        public Nullable<int> rating_star { get; set; }
        public Nullable<decimal> rating_official_D { get; set; }
        public Nullable<decimal> rating_official_E { get; set; }
        public Nullable<decimal> penalty { get; set; }
        public System.DateTime timestamp { get; set; }
        public string note { get; set; }
        public Nullable<int> vaultnumber_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public bool deleted { get; set; }
        public byte[] thumbnail { get; set; }
        public Nullable<int> vaultkind_id { get; set; }
        public Nullable<System.TimeSpan> synchronization_point { get; set; }
    
        public virtual gymnast gymnast { get; set; }
        public virtual location location { get; set; }
        public virtual vaultnumber vaultnumber { get; set; }
        public virtual vaultkind vaultkind { get; set; }
    }
}
